# Generated by Django 5.0.2 on 2025-09-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('post_type', models.CharField(choices=[('job', 'Job'), ('result', 'Result'), ('admitcard', 'Admit Card'), ('update', 'Important Update')], default='job', max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='images/pti')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('job_categories', models.ManyToManyField(blank=True, related_name='posts', to='firstapp.jobcategory')),
                ('qualifications', models.ManyToManyField(blank=True, related_name='posts', to='firstapp.qualification')),
                ('states', models.ManyToManyField(blank=True, related_name='posts', to='firstapp.state')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
