# Generated by Django 5.0.2 on 2025-09-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_jobcategory_name_alter_jobcategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='job_categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='post',
            name='states',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
