# Generated by Django 5.0.2 on 2025-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_job_remove_post_job_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_categories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='firstapp.jobcategory'),
        ),
    ]
