# Generated by Django 5.0.2 on 2025-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_jobcategory_job_job_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_categories',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
