# Generated by Django 5.0.2 on 2025-09-22 13:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_job_job_categories_job_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='h1',
            field=models.CharField(default='', max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='tag',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=550),
        ),
    ]
