# Generated by Django 5.0.2 on 2025-09-22 14:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_job_h1_job_tag_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='How_to_appply',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='How_to_appply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='application_fee',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='application_fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='author',
            field=django_ckeditor_5.fields.CKEditor5Field(default='  ', verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='eligibillity_criteria',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='eligibillity_criteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='important_dates',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='important_dates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='important_link',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='important_link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(default='    ', verbose_name='overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_structure',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='salary_structure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='selection_process',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='selection_process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy_details',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='vacancy_details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
    ]
