# Generated by Django 5.0.2 on 2025-09-24 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_job_how_to_appply_job_application_fee_job_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='faq_a1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='faq_q1',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='faq_q2',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
