# Generated by Django 5.0.2 on 2025-09-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_job_faq_a10_job_faq_a2_job_faq_a3_job_faq_a4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alternate text for OG Image (used in og:image:alt)', max_length=255, null=True),
        ),
    ]
