# Generated by Django 5.0.2 on 2025-09-24 17:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_job_image_job_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra_information',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='extra_information'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alternate text for OG Image (used in og:image:alt)', max_length=1000, null=True),
        ),
    ]
