# Generated by Django 5.0.2 on 2025-10-14 11:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_admitcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitcard',
            name='How_to_appply',
        ),
        migrations.AddField(
            model_name='admitcard',
            name='check_download',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='check_download'),
            preserve_default=False,
        ),
    ]
