# Generated by Django 5.0.2 on 2025-10-14 12:09

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_remove_admitcard_how_to_appply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Govtupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('h1', models.CharField(max_length=550)),
                ('author', django_ckeditor_5.fields.CKEditor5Field(verbose_name='author')),
                ('extra_information', django_ckeditor_5.fields.CKEditor5Field(verbose_name='extra_information')),
                ('overview', django_ckeditor_5.fields.CKEditor5Field(verbose_name='overview')),
                ('important_dates', django_ckeditor_5.fields.CKEditor5Field(verbose_name='important_dates')),
                ('vacancy_details', django_ckeditor_5.fields.CKEditor5Field(verbose_name='vacancy_details')),
                ('eligibillity_criteria', django_ckeditor_5.fields.CKEditor5Field(verbose_name='eligibillity_criteria')),
                ('application_fee', django_ckeditor_5.fields.CKEditor5Field(verbose_name='application_fee')),
                ('selection_process', django_ckeditor_5.fields.CKEditor5Field(verbose_name='selection_process')),
                ('salary_structure', django_ckeditor_5.fields.CKEditor5Field(verbose_name='salary_structure')),
                ('check_download', django_ckeditor_5.fields.CKEditor5Field(verbose_name='check_download')),
                ('important_link', django_ckeditor_5.fields.CKEditor5Field(verbose_name='important_link')),
                ('faq_q1', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a1', models.TextField(blank=True, null=True)),
                ('faq_q2', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a2', models.TextField(blank=True, null=True)),
                ('faq_q3', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a3', models.TextField(blank=True, null=True)),
                ('faq_q4', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a4', models.TextField(blank=True, null=True)),
                ('faq_q5', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a5', models.TextField(blank=True, null=True)),
                ('faq_q6', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a6', models.TextField(blank=True, null=True)),
                ('faq_q7', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a7', models.TextField(blank=True, null=True)),
                ('faq_q8', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a8', models.TextField(blank=True, null=True)),
                ('faq_q9', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a9', models.TextField(blank=True, null=True)),
                ('faq_q10', models.CharField(blank=True, max_length=555, null=True)),
                ('faq_a10', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='og_images/')),
                ('image_alt', models.CharField(blank=True, help_text='Alternate text for OG Image (used in og:image:alt)', max_length=1000, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
