# Generated by Django 5.0.2 on 2025-10-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_govtupdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Govtupdates',
            new_name='Govtupdate',
        ),
    ]
