# Generated by Django 5.0.2 on 2025-10-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_rename_govtupdates_govtupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govtupdate',
            name='check_download',
        ),
        migrations.RemoveField(
            model_name='govtupdate',
            name='salary_structure',
        ),
    ]
