# Generated by Django 5.0.2 on 2025-10-14 16:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_remove_govtupdate_check_download_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govtupdate',
            name='vacancy_details',
        ),
        migrations.AddField(
            model_name='govtupdate',
            name='details',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='details'),
            preserve_default=False,
        ),
    ]
