# Generated by Django 5.0.2 on 2025-10-15 10:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_remove_govtupdate_vacancy_details_govtupdate_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='title'),
        ),
    ]
