# Generated by Django 5.0.2 on 2025-10-15 18:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='h1',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='h1'),
        ),
    ]
