# Generated by Django 5.0.2 on 2025-10-16 02:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_alter_job_h1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOxname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('box1', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box2', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box3', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box4', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box5', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box6', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box7', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box8', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box9', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
                ('box10', django_ckeditor_5.fields.CKEditor5Field(verbose_name='box1')),
            ],
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='h1',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='h1'),
        ),
        migrations.AlterField(
            model_name='govtupdate',
            name='h1',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='h1'),
        ),
        migrations.AlterField(
            model_name='result',
            name='h1',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='h1'),
        ),
    ]
