# Generated by Django 5.0.2 on 2025-10-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_boxname_alter_admitcard_h1_alter_govtupdate_h1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxname',
            name='box10',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box2',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box3',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box4',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box5',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box6',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box7',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box8',
        ),
        migrations.RemoveField(
            model_name='boxname',
            name='box9',
        ),
    ]
