# Generated by Django 5.0.2 on 2025-10-16 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_remove_boxname_box10_remove_boxname_box2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxname',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
