# Generated by Django 5.0.2 on 2025-11-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='admission',
            new_name='job',
        ),
    ]
