# Generated by Django 5.0.2 on 2025-11-05 03:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_rename_admission_comment_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='JobComment',
        ),
    ]
