# Generated by Django 5.0.2 on 2025-11-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_admitcardcomment_govtupdatecomment_resultcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admitcardcomment',
            old_name='job',
            new_name='admitcard',
        ),
        migrations.RenameField(
            model_name='govtupdatecomment',
            old_name='job',
            new_name='govtupdate',
        ),
        migrations.RenameField(
            model_name='resultcomment',
            old_name='job',
            new_name='result',
        ),
    ]
