# Generated by Django 5.0.2 on 2026-01-13 14:26

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_admitcardcomment_govtupdatecomment_resultcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='admitcardcomment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='govtupdatecomment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='resultcomment',
            name='job',
        ),
        migrations.AddField(
            model_name='admitcard',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='admitcardcomment',
            name='admitcard',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='firstapp.admitcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='govtupdate',
            name='how_to_apply_online',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='how_to_apply_online'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='govtupdate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='govtupdate',
            name='syllabus',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='syllabus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='govtupdatecomment',
            name='govtupdate',
            field=models.ForeignKey(default='  ', on_delete=django.db.models.deletion.CASCADE, to='firstapp.govtupdate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='resultcomment',
            name='result',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='firstapp.result'),
            preserve_default=False,
        ),
    ]
