# Generated by Django 5.0.2 on 2025-11-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_rename_job_admitcardcomment_admitcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcardcomment',
            name='admitcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.admitcard'),
        ),
        migrations.AlterField(
            model_name='govtupdatecomment',
            name='govtupdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.govtupdate'),
        ),
        migrations.AlterField(
            model_name='resultcomment',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.result'),
        ),
    ]
