# Generated by Django 5.0.2 on 2025-11-14 15:22

import firstapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_alter_admitcardcomment_admitcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to=firstapp.models.pdf_upload_path)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
