# Generated by Django 5.2.6 on 2025-11-21 09:37

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_notification_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='h1',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='h1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Yahan PDF ka text paste karein (clean / formatted).', verbose_name='content'),
        ),
    ]
