# Generated by Django 5.2.6 on 2025-11-21 09:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_notification_category_notification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='author',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='author'),
            preserve_default=False,
        ),
    ]
