# Generated by Django 5.2.6 on 2025-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_notification_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcard',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter SEO keywords separated by comma. Example: government jobs, wb primary teacher, latest jobs 2025'),
        ),
        migrations.AddField(
            model_name='govtupdate',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter SEO keywords separated by comma. Example: government jobs, wb primary teacher, latest jobs 2025'),
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter SEO keywords separated by comma. Example: government jobs, wb primary teacher, latest jobs 2025'),
        ),
        migrations.AddField(
            model_name='notification',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter SEO keywords separated by comma. Example: government jobs, wb primary teacher, latest jobs 2025'),
        ),
        migrations.AddField(
            model_name='result',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter SEO keywords separated by comma. Example: government jobs, wb primary teacher, latest jobs 2025'),
        ),
    ]
