# Generated by Django 5.0.2 on 2025-11-28 11:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_admitcard_keywords_govtupdate_keywords_job_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='govtupdate',
            name='how_to_apply_online',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='how_to_apply_online'),
            preserve_default=False,
        ),
    ]
