# Generated by Django 5.0.2 on 2025-11-28 11:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0041_govtupdate_how_to_apply_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='govtupdate',
            name='syllabus',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='syllabus'),
            preserve_default=False,
        ),
    ]
