# Generated by Django 5.0.2 on 2025-12-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0045_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='overview',
        ),
    ]
