# Generated by Django 5.0.2 on 2025-12-03 14:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0046_rename_content_notification_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.AlterField(
            model_name='notification',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Yahan PDF ka text paste karein (clean / formatted).', verbose_name='overview'),
        ),
    ]
