# Generated by Django 5.0.2 on 2025-12-05 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0047_remove_notification_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
