"""
Django settings for wifiproject project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q(3djmhgp52&yzedeikg415exg5p1@a-lk!_3%9jxh6s1sw5^7'

# SECURITY WARNING: don't run with debug turned on in production!

# Production में जाते समय False Rakhna chahiyen;
# PING_ALWAYS = False

DEBUG = True
# DEBUG = False   # 404 template तभी दिखेगा जब DEBUG=False हो
SITE_ID = 1  
# ALLOWED_HOSTS = ["localhost", "127.0.0.1", '3.80.59.222', "www.wifiresult.com", "wifiresult.com"]
ALLOWED_HOSTS = ["localhost", "127.0.0.1", '192.168.1.4', "www.wifiresult.com", "wifiresult.com"]

# Application definition

INSTALLED_APPS = [
    # "jazzmin", 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # WhiteNoise ke liye yeh line staticfiles ke pehle
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    "firstapp.apps.FirstappConfig",
    "django_ckeditor_5",
    'django.contrib.sites',
    "django.contrib.sitemaps",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise middleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
APPEND_SLASH = True

ROOT_URLCONF = 'wifiproject.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wifiproject.wsgi.application'


# sylite3 Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# mysql Database

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "wifiresultcom",
#         "USER": "root",
#         "PASSWORD": "Asder567@",  # right password
#         "HOST": "127.0.0.1",
#         "PORT": "3306",
#         'OPTIONS': {
#     'charset': 'utf8mb4',
# },  } }



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_URL='static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_ROOT = BASE_DIR / "staticfiles"   # collectstatic यहीं files store करेगा
# WhiteNoise storage (compressed + cache-busted filenames)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_ROOT=os.path.join(BASE_DIR,"media")

TIME_ZONE = "Asia/Kolkata"
USE_TZ = True


 
 




CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": [
                "heading", "|",
                "bold", "italic", "underline", "strikethrough", "removeFormat", "|",
                "link", "blockQuote", "|",
                "code", "codeBlock", "|",
                "subscript", "superscript", "|",
                "highlight", "|",   # ⟵ highlight ko dropdown ke saath dikhayega
                "bulletedList", "numberedList", "todoList", "|",
                "outdent", "indent", "|",
                "alignment", "|",
                "insertTable", "|",
                "imageUpload", "mediaEmbed", "|",
                "fontSize", "fontFamily", "fontColor", "fontBackgroundColor", "|",
                "undo", "redo", "sourceEditing"
            ],
            "shouldNotGroupWhenFull": True
            
        },

        # ➕ Headings: h1–h6 (no other changes)
        "heading": {
            "options": [
                { "model": "paragraph", "title": "Paragraph", "class": "ck-heading_paragraph" },
                { "model": "heading1", "view": "h1", "title": "Heading 1", "class": "ck-heading_heading1" },
                { "model": "heading2", "view": "h2", "title": "Heading 2", "class": "ck-heading_heading2" },
                { "model": "heading3", "view": "h3", "title": "Heading 3", "class": "ck-heading_heading3" },
                { "model": "heading4", "view": "h4", "title": "Heading 4", "class": "ck-heading_heading4" },
                { "model": "heading5", "view": "h5", "title": "Heading 5", "class": "ck-heading_heading5" },
                { "model": "heading6", "view": "h6", "title": "Heading 6", "class": "ck-heading_heading6" }
            ]
        },

        # 🔶 Highlight plugin full setup
        "highlight": {
            "options": [
                { "model": "yellowMarker", "class": "marker-yellow", "title": "Yellow marker",
                  "color": "var(--ck-highlight-marker-yellow)", "type": "marker" },
                { "model": "greenMarker",  "class": "marker-green",  "title": "Green marker",
                  "color": "var(--ck-highlight-marker-green)",  "type": "marker" },
                { "model": "pinkMarker",   "class": "marker-pink",   "title": "Pink marker",
                  "color": "var(--ck-highlight-marker-pink)",   "type": "marker" },
                { "model": "blueMarker",   "class": "marker-blue",   "title": "Blue marker",
                  "color": "var(--ck-highlight-marker-blue)",   "type": "marker" },

                { "model": "redPen",       "class": "pen-red",       "title": "Red pen",
                  "color": "var(--ck-highlight-pen-red)",       "type": "pen" },
                { "model": "greenPen",     "class": "pen-green",     "title": "Green pen",
                  "color": "var(--ck-highlight-pen-green)",     "type": "pen" }
            ]
        },

        # 🧩 Table Configuration (as-is)
        "table": {
            "contentToolbar": [
                "tableColumn", "tableRow", "mergeTableCells",
                "tableProperties", "tableCellProperties"
            ],
            "tableProperties": {
                "borderColors": [
                    {"color": "#000000", "label": "Black"},
                    {"color": "#cccccc", "label": "Light gray"},
                    {"color": "#ff0000", "label": "Red"}
                ],
                "backgroundColors": [
                    {"color": "#ffffff", "label": "White"},
                    {"color": "#f8f8f8", "label": "Light"}
                ]
            },
            "tableCellProperties": {
                "borderColors": [
                    {"color": "#000000", "label": "Black"},
                    {"color": "#cccccc", "label": "Light gray"}
                ],
                "backgroundColors": [
                    {"color": "#ffffff", "label": "White"},
                    {"color": "#f0f8ff", "label": "Light blue"}
                ]
            }
        },

        # 🧱 Allow inline styles/attributes/classes (highlight ke classes bhi allow)
        "htmlSupport": {
            "allow": [
                # existing allows ...
                { "name": "table", "attributes": True, "classes": True,
                  "styles": ["border", "border-color", "border-width", "border-style"] },
                { "name": "th", "attributes": True, "classes": True,
                  "styles": ["border", "border-color", "border-width", "border-style"] },
                { "name": "td", "attributes": True, "classes": True,
                  "styles": ["border", "border-color", "border-width", "border-style"] },
                { "name": "p", "styles": ["text-align"] },
                { "name": "span", "styles": ["font-size", "color", "background-color", "text-align"], "classes": True },

                # ✅ Highlight output allow (CKEditor default <mark class="marker-..."> / <span class="pen-...">)
                { "name": "mark", "attributes": True, "classes": True, "styles": True },
                { "name": "span", "classes": ["pen-red", "pen-green",
                                              "marker-yellow", "marker-green", "marker-pink", "marker-blue"] }
            ]
        },

        # 🌐 Font size options
        "fontSize": {
            "options": [8, 10, 12, 14, "default", 16, 17, 18, 24, 32, 48],
            "supportAllValues": True
        },

        # 🧭 Alignment
        "alignment": { "options": ["left", "center", "right", "justify"] },

        "language": "en"
    }
}




# Django material


from django.templatetags.static import static

JAZZMIN_SETTINGS = {
    "site_title": "WifiResult",           # ब्राउज़र टैब का टाइटल
    "site_header": "WifiResult Admin Panel ",           # पेज पर ऊपर दिखने वाला हेडर
    "site_brand": "WifiResult",                # ब्रांड नाम (Logo के पास)
    "welcome_sign": "Welcome to My Dashboard signup", # लॉगिन स्क्रीन का मैसेज
    "copyright": "© 2025 My Company", #admin panal main sabse niche hota hai;
    "site_logo": "image.png",  # STATIC फोल्डर के अंदर इमेज पथ दें
    "navigation_expanded": False,
}



#setting.py
LOGIN_URL = 'login'


#message 
from django.contrib.messages import constants as messages

MESSAGE_TAGS={
    messages.ERROR:'danger'
}



# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True




# PDF ko same domain ke iframe me open karne ke liye
X_FRAME_OPTIONS = "SAMEORIGIN"


# pdf compress
from django import forms

class PDFUploadForm(forms.Form):
    pdf_file = forms.FileField(label="Upload PDF")
